version: '2'

services:
  peril_dev:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - .:/app
    command: yarn compile
    environment:
    # replace the following envvars with yours
      PRIVATE_GITHUB_SIGNING_KEY: |
        -----BEGIN RSA PRIVATE KEY-----
        MIIEpQIBAAKCAQEA7FZ0DtQarhPZIxGj5ZH3PlMBf9DoaZOnuXXPb2yD6QiTFH1h
        uaT26mRflYmtWC1eMErzPnI74BCyvURuZoPvFo3+jcIPJq2CsaA/DUE4mwOziHsq
        wP9jdUEX2FRbPEM0hQyzAyy49osDvri2GJEsTfZfrzauRbFd1bMbSOaEDvPeAjrb
        aODppI/MY9UfhVas1Yg74jiI6EzoyHt+bE48Q6VuU54hJcWuLqUUv9hzsDhxrpEO
        OgRMj8DhbzzUL2dSAM9EpE1E8OMPjRlYW6xYIwo+58sTGbjtvJl6vFhWCLXUeufK
        3nSlSyf3jkWXdN2i6faKW0X4Clbb3YUKMDMrEwIDAQABAoIBAQDTjlwbfgBX/Ups
        2viUosHol1MLQE0bXOJR4MSMIF5ANr26JLZbAPFKRglOCc0S1qGupxjwuD8ixq/J
        Pr14pPdbgEXyTVlUrRMFv8VRLyXllT2bmW1fD/3O0zLuIiz9V8dmpkSEPf9gKnZy
        vlO60BERxM5IQLFlj2zIw6hT7I0f97JDDtZ7cKBQvzVswnqXdjqcqVUzRnWJmOBq
        G1aRqZU8BOdsBVYnCMMqkISX+yDtZDtk8C2zyoOEw4eyqK78naHeMf3U3ovfqluv
        w6f9/ZVmsWiCot9F4MKNqQOkcdcWW8BOIYYpsmJEcDsRR1hJ7o+yl2vckoluZhe8
        FFi0EHNxAoGBAPnTZPDc1S31ZBxXAcFzhf7olJlCxDpnTCY3KU6TmUCh23Cj8r1l
        Dxz4rVOo+QzB2ZfoexOVQyXElXbLCUmxEjMW+VHe2vIhmkgg7kLtblM1owIhnWw4
        znl5xy7OxRuVeAuaMJqB3W+P4bxV6XknUjMLmvFKGVbABQjkR+ndbLKLAoGBAPIt
        uPA/0Ji2Igeqcw/lvw7m5AN6bebG704QZjEZUgxXsjX9/KjZ76GZg+ioYiq7FSFX
        0wBUZja6l2nLRLbEUxOPRnWDtq7Sshwiu8LJc3k9/5amYvxz+FVYp76G7/byP9HV
        LtMRYP2F0Owp/zUCveNWXpJwRaOEH8Mxh+ruUiKZAoGBAO7qdodOeeUI36Ompbwu
        0b+VB7+GNYkxDochi7RkvVQtNmIDuHnd8tUfEQuH9h14KbL4FvQEdAHjfZjs1UYP
        PDt1xhvAx5x1/EjsjU+eJzsWeXzpTtaXgQZ1KsKd5azahcJ6w+6PMYimjhgCBVTj
        AN5mQ9hrp83ptybowclrA6+/AoGBAM954GDjKwBJuSm8G0tZVq+bm2hncNQvRkEo
        x4P031f3oZOj/tthqmxVqq6d40wcbuPb68byh4cHoERggoPZ+hpdus1ehBmOJEz6
        bMVZ9PW/6cHU1iTV7cCgbUVLMTXtIEPSUYU99Ev+YpiQ+jUeHjQvgGIQkXie7t85
        Bep9NhyxAoGARCQjr2u4oAOhYD5/+Xdi9CfCZeR4NmvrVMAX8X117DXu2tYe7xsu
        l+RCoHD6RBTm7zGuLzXd7iqicAXDyDkoEBDT8s7MeWVTLVGJd+AhoquuQm9SQO7n
        Xr6gdKXTH+oo8RTvBqhepvW5GvTaaPZS9wZKzey7oUp6ItJPUEEZmSA=
        -----END RSA PRIVATE KEY-----
      PERIL_INTEGATION_ID: 1234
      DATABASE_URL: localhost:5432
      WEB_URL: http://danger.systems
  ngrok:
    image: wernight/ngrok
    links:
      - "peril"
    command: "ngrok http peril:5000"
    ports:
      - "4040:4040"
